#!/bin/sh
echo "XXXXXX:"+$@
if [ $1 = 'server' ]
then
	my=172.20.20.1
	peer=172.20.20.2
  /sbin/ifconfig $2 $my pointopoint $peer up
else
	my=172.20.20.2
	peer=172.20.20.1
  /sbin/ifconfig $2 $my pointopoint $peer up
  /sbin/ip route del 10.9.24.0/23 dev eth0.16  proto kernel  scope link  src 10.9.24.1 table congress
  /sbin/ip route del default via $peer dev $2 table congress
  /sbin/ip rule  del from 10.9.24.0/23 table congress

  /sbin/ip route add 10.9.24.0/23 dev eth0.16  proto kernel  scope link  src 10.9.24.1 table congress
  /sbin/ip route add default via $peer dev $2 table congress
  /sbin/ip rule  add from 10.9.24.0/23 table congress
fi


#route add -net 172.21.21.0 netmask 255.255.255.0 gw 172.20.20.2
#ifconfig tun1 172.20.20.2 172.20.20.1 up
#route add -net 172.21.21.0 netmask 255.255.255.0 gw 172.20.20.2
#ping 172.20.20.1

